version: '3'
services:

  event_store:
      container_name: event_store
      image: mongo
      restart: always
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=event_store_db
      ports:
          - '27017:27017'
      networks:
          - my_bridge_network

  materialized_view:
      container_name: materialized_view
      image: mongo
      restart: always
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=materialized_view_db
      ports:
          - '27018:27017'
      networks:
          - my_bridge_network
  zookeeper:
      container_name: zookeeper
      image: wurstmeister/zookeeper
      ports:
          - '2181:2181'
      networks:
          - my_bridge_network

  kafka_broker:
      image: wurstmeister/kafka
      ports:
          - '9092:9092'
          - '29092:29092'
      links:
          - zookeeper
      depends_on:
          - zookeeper
      environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
          - KAFKA_LISTENERS=PLAINTEXT://:9092
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_broker:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
          - KAFKA_CREATE_TOPICS=account_topic:1:1
      networks:
          - my_bridge_network

  axon_command:
        build:
          context: .
          dockerfile: Dockerfile_axon_command.dev
        container_name: axon_command
        depends_on:
          - event_store
          - kafka_broker
        environment:
          - SPRING_DATA_MONGODB_HOST=event_store
          - SPRING_DATA_MONGODB_PORT=27017
          - SPRING_DATA_MONGODB_DATABASE=event_store_db
          - SPRING_DATA_MONGODB_USERNAME=admin
          - SPRING_DATA_MONGODB_PASSWORD=admin
          - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
          - AXON_SERIALIZER_GENERAL=jackson
          - AXON_KAFKA_CLIENT-ID=accountproducer
          - AXON_KAFKA_DEFAULT-TOPIC=account_topic
          - AXON_KAFKA_PRODUCER_RETRIES=5
          - AXON_KAFKA_BOOTSTRAP-SERVERS=kafka_broker:9092
          - AXON_KAFKA_PRODUCER_TRANSACTION-ID-PREFIX=clxtrx
          - AXON_DISTRIBUTED_ENABLED=true
        ports:
          - '8080:8080'
        networks:
          - my_bridge_network
 
  axon_query:
        build:
           context: .
           dockerfile: Dockerfile_axon_query.dev
        container_name: axon_query
        depends_on:
           - materialized_view
           - kafka_broker
        environment:
           - SPRING_DATA_MONGODB_DATABASE=materialized_view_db
           - SPRING_DATA_MONGODB_HOST=materialized_view
           - SPRING_DATA_MONGODB_USERNAME=admin
           - SPRING_DATA_MONGODB_PASSWORD=admin
           - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
           - SPRING_DATA_MONGODB_PORT=27017
           - AXON_SERIALIZER_GENERAL=jackson
           - AXON_KAFKA_CLIENT-ID=accountproducer
           - AXON_KAFKA_DEFAULT-TOPIC=account_topic
           - AXON_KAFKA_CONSUMER_GROUP-ID=account_group
           - AXON_KAFKA_CONSUMER_AUTO-OFFSET-RESET=earliest
           - AXON_KAFKA_BOOTSTRAP-SERVERS=kafka_broker:9092
           - AXON_KAFKA_PRODUCER_TRANSACTION-ID-PREFIX=clxtrx
           - AXON_DISTRIBUTED_ENABLED=true
        ports:
           - '8081:8080'
        networks:
           - my_bridge_network
 
networks: 
  my_bridge_network:
    external: true 
